name: GrieferGames
author: Niklas409
version: 3.0
main: de.niklas409.griefergames.features.main.Main
commands:
     slowchat:
     clearchat:
     mutep:
     startkick:
     ja:
     nein:
     kopf:
     prefix:
     b:
     viewarmor:
     unmutep:
     unstartkick:
     rand:
     ggrl:
     luckyblock:
     ping:
     ban:
     unban:
     unmute:
     vanish:
     v:
     playerholo:
     clan:
     breakblock:
     blocklog:
     meldung:
     antibot:
     portal:
     bank:
     perk:
     premium:
     status:
     feuerwerk:
     gun:
     skin:
     merge:
     grieferboost:
     booster:
     menu:
     sign:
     schild:
     case:
     createcaseitem:
     setcaseblock:
     freekiste:
     dup:
     leuchten: